import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { ConvexClientProvider } from "@/components/convex-client-provider";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import Modal from "@/components/modal";
import { Toaster } from "@/components/ui/sonner";
import { JotaiProvider } from "@/components/ui/jotai-provider";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import "./globals.css";

const font = Poppins({
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
});

export const metadata: Metadata = {
  title: "Team ChatApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body className={font.className}>
          <ConvexClientProvider>
            <JotaiProvider>
              <Toaster />
              <Modal />
              <NuqsAdapter>
                {children}
              </NuqsAdapter>
            </JotaiProvider>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
